services:
  webapi:
    volumes:
      - ./src:/code
    build:
      dockerfile: webapi.Dockerfile
    ports:
      - "8080:8080"
  postgres:
    build:
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
