services:
  web:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:15.13-bookworm"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
